AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EC2InstanceName1a:
    Type: String
    Default: cf_aws-and-infra-web-1a
    AllowedValues: 
      - target
      - Bastion
      - cf_aws-and-infra-web-1a

  EC2InstanceName1c:
    Type: String
    Default: cf_aws-and-infra-web-1c
    AllowedValues: 
      - Bastion
      - Ansible
      - cf_aws-and-infra-web-1c
      - ec2-for-db

Resources: 
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
# VPC Create
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: cf_aws-and-infra-vpc

# InternetGateway Create
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: cf_aws-and-infra-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
#  Subnet
# -----------------------------------------------------#          
# Public Subnet1a Create
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: cf_aws-and-infra-public-subnet-1a

# Private Subnet1a Create
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: cf_aws-and-infra-private-subnet-1a

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#          
# Public RouteTable1a Create
  PublicRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: cf_aws-and-infra-public1a-route

# ------------------------------------------------------------#
# RouteTable Associate
# 読んで字のごとし。サブネットの関連付け
# ------------------------------------------------------------# 
# PublicRouteTable Associate PublicSubnet1a
  PublicSubnet1aRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable1a

# ------------------------------------------------------------#
# Routing
# ------------------------------------------------------------# 
# PublicRoute1a Create
  PublicRoute1a:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable1a
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
# EC2
# ------------------------------------------------------------# 
# SG Create
  EC2secGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-and-infra-web
      GroupDescription: aws-and-infra-web #required!
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

# DBSG Create
  RDSsecGroup:
    Type: AWS::EC2::SecurityGroup #EC2!!
    Properties:
      GroupName: cf_aws-and-infra-db
      GroupDescription: cf_aws-and-infra-db
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2secGroup
  
# EC2 Create
  EC2InstancePub:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: aws-and-infra-ssh-key
      ImageId: ami-09ebacdc178ae23b7
      InstanceType: t2.micro
      Monitoring: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet1a
          GroupSet:
            - !Ref EC2secGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum install -y tree
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName1a

  EC2InstancePri:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: aws-and-infra-ssh-key
      ImageId: ami-09ebacdc178ae23b7
      InstanceType: t2.micro
      Monitoring: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          SubnetId: !Ref PrivateSubnet1a
          GroupSet:
            - !Ref RDSsecGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum install -y tree
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName1c